# Wielkość ekranu
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# Ilość Płytek
TILES_IN_ROW = 40
TILES_IN_COL = 22.5
TILES_IN_COL_ROUNDED = 23

# Wielkość płytki
TILE_WIDTH = SCREEN_WIDTH / TILES_IN_ROW
TILE_HEIGHT = SCREEN_HEIGHT / TILES_IN_COL
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)


# Wielkość mapy
MAP_SIZE_X_AND_Y = 100
MAP_SIZE = (100, 100)

