# Wielkość ekranu
    # 32 X 32
        # SCREEN_WIDTH = 1312
        # SCREEN_HEIGHT = 736
    # 64 X 64
SCREEN_WIDTH = 1344
SCREEN_HEIGHT = 704
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

# Ilość Płytek
    # 32 X 32
        # TILES_IN_ROW = 41
        # TILES_IN_COL = 23
    # 64 X 64
TILES_IN_ROW = 21
TILES_IN_COL = 11


# Wielkość płytki
TILE_WIDTH = SCREEN_WIDTH / TILES_IN_ROW
TILE_HEIGHT = SCREEN_HEIGHT / TILES_IN_COL
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)


# Wielkość mapy
MAP_SIZE_X_AND_Y = 100
MAP_SIZE = (MAP_SIZE_X_AND_Y, MAP_SIZE_X_AND_Y)
